print ("Please enter the following information: \n")
first = input("First name: ")
last = input("Last name: ")
email = input("Email address: ")
phone = input("Phone number: ")
job = input("Job title: ")
id = input("ID Number: ")
hair = input("Hair: ")
eyes = input("Eyes: ")
month = input("Month of start: ")
training = input(" Have you completed advanced training? (Y/N): ")
print()
print("The ID Card is: ")
print("----------------------------------------------------------------")
print(last.upper(), first.title())
print(job.title())
print(id)
print()
print(email.lower())
print(phone)
print(f"{hair} {eyes:<15}")
print(f"{month} {training:<15}")
print("----------------------------------------------------------------")