print ("Please enter the following information: \n")
first = input("First name: ")
last = input("Last name: ")
email = input("Email address: ")
phone = input("Phone number: ")
job = input("Job title: ")
id = input("ID Number: ")
hair = input("Hair color: ")
eyes = input("Eyes color: ")
month = input("Starting month: ")
training = input("Have you completed advanced training? (Yes/No): ")
print()
print("The ID Card is: ")
print("----------------------------------------------------------------")
print(last.upper(), first.title())
print(job.title())
print(id)
print()
print(email.lower())
print(phone)
print(f"{'Hair: '+hair:<20}{'Eyes: '+eyes:<20}")
print(f"{'Month: '+month:<20}{'Training: '+training:<20}")
print("----------------------------------------------------------------")